project:
  type: website

website:
  title: "Carson Zhang"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: house-fill
        href: https://www.carsonzhang.com
format:
  html:
    theme: lumen
    css: styles.css

execute:
  freeze: auto


