project:
  type: website

website:
  title: "Carson Zhang"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: 
      light: [lumen, theme-light.scss]
    css: styles.css



